[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
; CHANGE THIS to your actual port:
monitor_port = COM17   ; ← YOUR ESP32 IS ON COM17!

upload_port = COM17

lib_deps = 
    mikalhart/TinyGPSPlus@^1.0.3